scoreTransfer:
  enable: true
  port: 8082
  webEnable: true
  batchSize: 4
  enterTimeoutSeconds: 120
  trackTimeoutSeconds: 120
  fillRemainingTracks: true
  uploadTimeoutSeconds: 60
  logoutTimeoutSeconds: 60
  loginTimeoutSeconds: 120
  loginWaitSeconds: 0
  songWaitSeconds: 30
dummyLogin:
  enable: true
  defaultUserId: 1
