scoreTransfer:
  enable: true
  port: 8082
  webEnable: true
  batchSize: 4
  enterTimeoutSeconds: 120
  trackTimeoutSeconds: 300
  fillRemainingTracks: true
  uploadTimeoutSeconds: 60
  logoutTimeoutSeconds: 60
  loginTimeoutSeconds: 120
  minSessionSeconds: 120
  songWaitSeconds: 0
  playWaitSeconds: 60
  fullPlay: true
  autoContinue: true
dummyLogin:
  enable: true
  defaultUserId: 1
