scoreTransfer:
  enable: true
  port: 8082
  webEnable: true
  batchSize: 4
  enterTimeoutSeconds: 120
  trackTimeoutSeconds: 120
  fillRemainingTracks: true
  uploadTimeoutSeconds: 60
  logoutTimeoutSeconds: 60
  loginTimeoutSeconds: 120
dummyLogin:
  enable: true
  defaultUserId: 1
fix:
  enable: false
  disableEnvironmentCheck: true
  disableEncryption: false
  disableReboot: false
  fixCheckAuth: false
  skipCakeHashCheck: false
  skipSpecialNumCheck: false
  skipVersionCheck: false
